/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import com.google.gson.JsonSyntaxException;
import controlador.Consultas;
import controlador.ConsultasPedidos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import modelo.Mesa;
import modelo.Mesas_Pedidos;
import modelo.Pedido;
import modelo.Usuario;
import org.joda.time.DateTime;
import utilidades.RespuestaJson;

/**
 *
 * @author negu2
 */
public class GestionMesas_Pedidos extends javax.swing.JPanel {

    private DefaultTableModel modeloTablaPedidos = new DefaultTableModel();
    private SpinnerNumberModel modeloSpinnerNumMesa = new SpinnerNumberModel();
    
    /**
     * Creates new form GestionMesas_Pedidos
     */
    public GestionMesas_Pedidos() {
        initComponents();
        llenarModeloPedidos();
        numMesasTotales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNumMesas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerIdPedido = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerNumMesa = new javax.swing.JSpinner();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerIdMesaPedido = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número de mesas: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, -1));

        jLabelNumMesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumMesas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        add(jLabelNumMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, 20));

        jTablePedidos.setModel(modeloTablaPedidos);
        jScrollPane1.setViewportView(jTablePedidos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 740, -1));

        jLabel2.setText("Id del pedido:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));
        add(jSpinnerIdPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel8.setText("Pedidos");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel3.setText("Eliga la mesa:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 20));

        jSpinnerNumMesa.setModel(modeloSpinnerNumMesa);
        add(jSpinnerNumMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel4.setText("Id:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 20));
        add(jSpinnerIdMesaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        //Comprobar si existe el pedido
        int idPedido = (int) jSpinnerIdPedido.getValue();
        int numMesa = (int) jSpinnerNumMesa.getValue();
        int idMesaPedido = (int) jSpinnerIdMesaPedido.getValue();
        Mesas_Pedidos mesaPedido = new Mesas_Pedidos(idMesaPedido, idPedido, numMesa);
        RespuestaJson respuestaJson = Consultas.insertar("mesas_pedidos", mesaPedido);
        JOptionPane.showMessageDialog(this, respuestaJson.getValue(), "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Comprobar si existe el pedido
        int idPedido = (int) jSpinnerIdPedido.getValue();
        int numMesa = (int) jSpinnerNumMesa.getValue();
        int idMesaPedido = (int) jSpinnerIdMesaPedido.getValue();
        Mesas_Pedidos mesaPedido = new Mesas_Pedidos(idMesaPedido, idPedido, numMesa);
        RespuestaJson respuestaJson = Consultas.actualizar("mesas_pedidos", mesaPedido);
        JOptionPane.showMessageDialog(this, respuestaJson.getValue(), "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Comprobar si existe el pedido
        int idPedido = (int) jSpinnerIdPedido.getValue();
        int numMesa = (int) jSpinnerNumMesa.getValue();
        int idMesaPedido = (int) jSpinnerIdMesaPedido.getValue();
        Mesas_Pedidos mesaPedido = new Mesas_Pedidos(idMesaPedido);
        RespuestaJson respuestaJson = Consultas.eliminar("mesas_pedidos", mesaPedido);
        JOptionPane.showMessageDialog(this, respuestaJson.getValue(), "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idMesaPedido = (int) jSpinnerIdMesaPedido.getValue();
        Mesas_Pedidos mesaPedido = new Mesas_Pedidos(idMesaPedido);
        try {
            mesaPedido = Consultas.existeMesas_Pedidos("mesas_pedidos", mesaPedido);
            jSpinnerIdPedido.setValue((int) mesaPedido.getIdPedido());
            jSpinnerNumMesa.setValue((int) mesaPedido.getNumMesa());
        } catch (JsonSyntaxException e) {
            JOptionPane.showMessageDialog(this, "Id no registrado en la BD", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

private void llenarModeloPedidos(){
        modeloTablaPedidos.addColumn("Id del Pedido");
        modeloTablaPedidos.addColumn("Trabajador");
        modeloTablaPedidos.addColumn("Cliente");
        modeloTablaPedidos.addColumn("Estado");
        modeloTablaPedidos.addColumn("Fecha pedido");
        modeloTablaPedidos.addColumn("Hora pedido");
        
        String nombreTrabajador = null, nombreCliente = null;
        int numFilas = modeloTablaPedidos.getRowCount();
        for (int i = 0; i < numFilas; i++) {
            modeloTablaPedidos.removeRow(0);
        }
        // Guardamos la fecha de hoy
        DateTime fechaActual = DateTime.now();
        String fechaHoy = fechaActual.toString().substring(0, 10);
        ArrayList<Pedido> pedidos = ConsultasPedidos.listarTodosLosPedidos();
        ArrayList<Usuario> usuarios = Consultas.ListarUsuarios();
        for (Pedido p : pedidos) {
            if (fechaHoy.equalsIgnoreCase(String.valueOf(p.getFechaHoraPedido().toString().substring(0, 10)))) {
                for (Usuario u : usuarios) {
                    if (u.getIdUsuario() == p.getIdTrabajador()) {
                        nombreTrabajador = u.getNombre();
                    } else if (u.getIdUsuario() == p.getIdCliente()) {
                        nombreCliente = u.getNombre();
                    }
                }
                String datos[] = {String.valueOf(p.getIdPedido()), nombreTrabajador, nombreCliente, p.getEstadoPedido(), String.valueOf(p.getFechaHoraPedido().toString().substring(0, 10)), p.getFechaHoraPedido().toString().substring(11, 16)};
                modeloTablaPedidos.addRow(datos);
            }
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNumMesas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerIdMesaPedido;
    private javax.swing.JSpinner jSpinnerIdPedido;
    private javax.swing.JSpinner jSpinnerNumMesa;
    private javax.swing.JTable jTablePedidos;
    // End of variables declaration//GEN-END:variables

    private void numMesasTotales() {
        ArrayList<Mesa> mesas = Consultas.ListarMesas();
        int mesasTotales = 0;
        for (Mesa m : mesas) {
            mesasTotales = m.getNumMesa();
        }
        jLabelNumMesas.setText("" + mesasTotales);
        modeloSpinnerNumMesa.setMaximum(mesasTotales);
        modeloSpinnerNumMesa.setMinimum(1);
        modeloSpinnerNumMesa.setStepSize(1);
        modeloSpinnerNumMesa.setValue((int) 1);
    }
}
