/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;

import controlador.Consultas;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Mesas_Pedidos;
import modelo.Pedido;
import modelo.Producto;
import modelo.Productos_Pedidos;
import utilidades.RespuestaJson;

/**
 *
 * @author negu2
 */
public class Pedido_Mesa extends javax.swing.JDialog {

    private DefaultListModel modelo = new DefaultListModel();
    private int numPedido = 0;
    
    /**
     * Creates new form Pedido_Mesa
     */
    public Pedido_Mesa(java.awt.Frame parent, boolean modal,int numMesa) {
        super(parent, modal);
        initComponents();
        comprobarMesaPedido(numMesa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProductosPedido = new javax.swing.JList<>();
        jLabelIdPedido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrecioTotal = new javax.swing.JLabel();
        panelPagar = new javax.swing.JPanel();
        etiquetaLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel8.setText("Ticket");

        jLabel1.setText("Número pedido:");

        jListProductosPedido.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jListProductosPedido.setModel(modelo);
        jScrollPane1.setViewportView(jListProductosPedido);

        jLabelIdPedido.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabelIdPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdPedido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));

        jLabel2.setText("Precio Total: ");

        jLabelPrecioTotal.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabelPrecioTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecioTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));

        panelPagar.setBackground(new java.awt.Color(153, 153, 153));
        panelPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPagarMouseClicked(evt);
            }
        });

        etiquetaLogin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        etiquetaLogin.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaLogin.setText("Pagar");

        javax.swing.GroupLayout panelPagarLayout = new javax.swing.GroupLayout(panelPagar);
        panelPagar.setLayout(panelPagarLayout);
        panelPagarLayout.setHorizontalGroup(
            panelPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(etiquetaLogin)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelPagarLayout.setVerticalGroup(
            panelPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(etiquetaLogin)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoTicket.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(219, 219, 219))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(panelPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPagarMouseClicked
        int eleccion = JOptionPane.showConfirmDialog(this,"¿Estas seguro de que quieres modificar el estado del pedido?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (eleccion == JOptionPane.YES_OPTION) {
            RespuestaJson respuestaJson = Consultas.actualizarPedido(new Pedido(numPedido,"Pagado"));
            JOptionPane.showMessageDialog(this, respuestaJson.getValue(),"Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_panelPagarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelIdPedido;
    private javax.swing.JLabel jLabelPrecioTotal;
    private javax.swing.JList<String> jListProductosPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPagar;
    // End of variables declaration//GEN-END:variables

    private void listarProductos() {
        double precioTotal = 0;
        ArrayList<Productos_Pedidos> productos_pedidos = Consultas.ListarProductos_Pedidos();
        ArrayList<Producto> productos = Consultas.ListarProductos();
        for (Productos_Pedidos producto_pedido : productos_pedidos) {
            numPedido = producto_pedido.getIdPedido();
            for (Producto producto : productos) {
                if (producto_pedido.getIdProducto() == producto.getIdProducto()) {
                    precioTotal = precioTotal + producto.getPrecioProducto()*producto_pedido.getCantidadProducto();
                    jLabelIdPedido.setText("" + producto_pedido.getIdPedido());
                    modelo.addElement(producto.getNombreProducto() + " ------> " + producto_pedido.getCantidadProducto() + " ------> " +  producto.getPrecioProducto()*producto_pedido.getCantidadProducto()+"€");
                }
            }
        }
        jLabelPrecioTotal.setText("" + precioTotal + "€");
    }

    private void comprobarMesaPedido(int numMesa) {
        ArrayList<Mesas_Pedidos> pedidosMesas = Consultas.ListarMesas_Pedidos();
        for (Mesas_Pedidos mp : pedidosMesas) {
            if (numMesa == mp.getNumMesa()) {
                listarProductos();
                this.setVisible(true);
            }
        }
        
    }
}
