/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.google.gson.Gson;
import com.google.gson.JsonSyntaxException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Usuario;
import utilidades.Constantes;
import utilidades.Decodificaciones;
import utilidades.HttpRequest;

/**
 *  Ventana que permite loguearse a la aplicacion
 * @author negu2
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Constructor de VentanaLogin
     */
    public VentanaLogin() {
        // Se inicia los componentes y se muestra
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        etiquetaSalida = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        etiquetaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 56, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 0, 310, 430));

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 270, -1));

        txtUsuario.setBackground(new java.awt.Color(105, 56, 41));
        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Ingrese nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 270, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 270, 10));

        txtPassword.setBackground(new java.awt.Color(105, 56, 41));
        txtPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("123455667890");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 270, -1));

        jPanel2.setBackground(new java.awt.Color(169, 124, 111));

        etiquetaSalida.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        etiquetaSalida.setForeground(new java.awt.Color(102, 0, 0));
        etiquetaSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSalida.setText("X");
        etiquetaSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiquetaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaSalidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(827, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaSalida)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 30));

        panelLogin.setBackground(new java.awt.Color(199, 161, 117));
        panelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLoginMouseClicked(evt);
            }
        });

        etiquetaLogin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        etiquetaLogin.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaLogin.setText("Entrar");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(etiquetaLogin)
                .addGap(30, 30, 30))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(etiquetaLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que cierra la aplicacion cuando se pulse en la X de la parte superior izquierda de la ventana.
     * @param evt --> Es el MouseEvent que necesita el metodo. 
     */
    private void etiquetaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaSalidaMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_etiquetaSalidaMouseClicked

    /**
     * Metodo que comprueba si los campos estan vacios o no.
     * @param evt --> Es el MouseEvent que necesita el metodo.
     */
    private void panelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLoginMouseClicked
        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        char[] Arraypassword = txtPassword.getPassword();
        String password = String.valueOf(Arraypassword);
        // Se comprueba el usuario si no esta en blanco o vacio
        if (!usuario.isEmpty()) {
            // se pasa a la password y si esto no esta vacio
            if (!password.isEmpty()) {
                // llamamos al siguiente metodo
                login(usuario, password);
            } else {
                // Si la password esta en blanco saltara el siguiente JOptionPane
                JOptionPane.showMessageDialog(this, "Campo de la password no relleno.", "Password", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Si el usuario esta en blanco saltara el siguiente JOptionPane
            JOptionPane.showMessageDialog(this, "Campo del usuario no relleno.", "Usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_panelLoginMouseClicked

    /**
     * Metodo para cuando cliques en el campo Usuario se vacie.
     * @param evt --> Es el MouseEvent que necesita el metodo.
     */
    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    /**
     * Metodo para cuando cliques en el campo Password se vacie.
     * @param evt --> Es el MouseEvent que necesita el metodo.
     */
    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioMouseClicked

    /**
     * Metodo para cuando pulses la tecla 'Up Arrow', el foco del cursor se posiciona 
     * en el campo que se encuentra en la parte superior.
     * @param evt --> Es el KeyEvent que necesita el metodo.
     */
    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        char teclaPulsada = (char) evt.getKeyCode();
        if (teclaPulsada == evt.VK_UP) {
            txtUsuario.requestFocus();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * Metodo para cuando pulses la tecla 'Down Arrow', el foco del cursor se posiciona 
     * en el campo que se encuentra en la parte inferior o si la tecla es el "Enter".  
     * @param evt --> Es el KeyEvent que necesita el metodo.
     */
    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        // TODO add your handling code here:
        char teclaPulsada = (char) evt.getKeyCode();
        if (teclaPulsada == evt.VK_ENTER) {
            txtPassword.requestFocus();
            txtPassword.setText("");
        } else if (teclaPulsada == evt.VK_DOWN) {
            txtPassword.requestFocus();
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    /**
    * Método que lee el usuario y la password que se le pasa como argumento 
    * y los comprueba si hay una coincidencia en la base de datos.
    * @param usuario --> Es el texto que contiene el campo usuario.
    * @param password --> Es el texto que contiene el campo password.
    */    
    private void login(String usuario, String password) {
        // Creamos un usuario con los dos parametros necesarios
        Usuario user = new Usuario(usuario, password);
        Gson gson = new Gson();
        // Lo convertimos en Json
        String jsonObject = gson.toJson(user);
        String values = "datos=" + jsonObject;
        // Se manda al webservice
        String respuesta = HttpRequest.GET_REQUEST(Constantes.URL_LOGUEO, values);
        // Intentamos decodificar el usuario, si no existe saltara el catch
        try {
            // Si lo decodificamos y nos manda un usuario
            user = Decodificaciones.deserializeUsuario(respuesta);
            // Se comprueba que tipo es si es trabajador, accede a la ventana principal
            if (user.getTipoUsuario().equalsIgnoreCase("Trabajador")) {
                new VentanaPrincipalEscritorio(user.getTelefono());
                dispose();
            } else {
                // Si no se muestra el siguiente mensaje
                JOptionPane.showMessageDialog(null, "No tienes permisos");
            }
        } catch (JsonSyntaxException e) {
            // Esto saltaria cuando en la bd no exista el usuario ni la password
            JOptionPane.showMessageDialog(this, "Datos no registrados en la base de datos", "Intentelo de nuevo", JOptionPane.ERROR_MESSAGE);
            txtUsuario.setText("");
            txtPassword.setText("");
            txtUsuario.requestFocus();
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaLogin;
    private javax.swing.JLabel etiquetaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
